const std = @import("std");
const assert = std.debug.assert;

const log = std.log.scoped(.@"xcb-scanner");

const xml = @import("xml.zig");

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const gpa = init.gpa;

    var protocols: std.ArrayList([]const u8) = .empty;
    defer protocols.deinit(gpa);

    var out_path_opt: ?[]const u8 = null;

    var args = init.minimal.args.iterate();

    while (args.next()) |arg| {
        if (std.mem.eql(u8, arg, "-i")) {
            const protocol_path = args.next() orelse return error.MissingArg;
            try protocols.append(gpa, protocol_path);
        } else if (std.mem.eql(u8, arg, "-o")) {
            out_path_opt = args.next() orelse return error.MissingArg;
        }
    }

    const out_path = out_path_opt orelse return error.MissingArg;
    log.info("{s}", .{out_path});

    var documents: std.ArrayList([]const u8) = .empty;
    defer {
        for (documents.items) |document|
            gpa.free(document);
        documents.deinit(gpa);
    }

    var protocol_parser: ProtocolParser = .init(gpa);
    defer protocol_parser.deinit();

    for (protocols.items, 0..) |protocol, i| {
        var protocol_file = try std.Io.Dir.openFileAbsolute(io, protocol, .{});
        defer protocol_file.close(io);
        var file_reader = protocol_file.reader(io, &.{});
        const document = try file_reader.interface.allocRemaining(gpa, .unlimited);
        try documents.append(gpa, document);

        var parser: xml.Parser = .init(document);
        log.info("[{d}/{d}] {s}", .{ i + 1, protocols.items.len, std.Io.Dir.path.basename(protocol) });
        try protocol_parser.parse(&parser);
    }

    var ir: Ir = .init(gpa);
    defer ir.deinit();
    try ir.parse(protocol_parser);

    var buffer: std.Io.Writer.Allocating = .init(gpa);
    const writer = &buffer.writer;
    try writer.writeAll(
        \\//! Generated by xcb-scanner
        \\
        \\
    );
    try writer.writeAll(@embedFile("core.zig"));
    try writer.writeByte('\n');

    const emitter = try ir.emitter(writer);
    try emitter.emit();
    emitter.deinit();

    const generated = try buffer.toOwnedSliceSentinel(0);
    defer gpa.free(generated);

    var zig_tree = try std.zig.Ast.parse(gpa, generated, .zig);
    defer zig_tree.deinit(gpa);

    const out_file = try std.Io.Dir.createFileAbsolute(io, out_path, .{});
    defer out_file.close(io);

    if (zig_tree.errors.len != 0) {
        try std.zig.printAstErrorsToStderr(gpa, io, zig_tree, out_path, .auto);
        try out_file.writeStreamingAll(io, generated);
        return error.EmitError;
    }

    var out_buf: [4096]u8 = undefined;
    var out_writer = out_file.writer(io, &out_buf);

    try zig_tree.render(gpa, &out_writer.interface, .{});

    try out_writer.interface.flush();

    var usage: std.os.linux.rusage = undefined;
    _ = std.os.linux.getrusage(std.os.linux.rusage.SELF, &usage);
    log.info("max RSS: {d}\n", .{usage.maxrss});
}

pub const ProtocolParser = struct {
    gpa: std.mem.Allocator,
    tree: Tree,

    pub const Tree = FamilyTree(NodeValue);
    pub const Node = Tree.Node;

    pub const NodeValue = union(enum) {
        root,
        xcb: struct {
            header: []const u8 = "invalid",
            @"extension-xname": ?[]const u8 = null,
            @"extension-name": ?[]const u8 = null,
            @"extension-multiword": bool = false,
            @"major-version": u8 = 0,
            @"minor-version": u8 = 0,
        },
        import: []const u8,
        typedef: struct { oldname: []const u8, newname: []const u8 },
        type: []const u8,
        xidtype: Name,
        xidunion: Name,
        @"enum": Name,
        enumref: struct { ref: []const u8 },
        item: Name,
        value: u64,
        bit: u8,
        @"struct": Name,
        @"union": Name,
        request: struct { name: []const u8, opcode: u8 },
        reply: void,

        event: struct { name: []const u8, number: u32 },
        eventcopy: Copy,
        eventstruct: Name,
        allowed: struct { extension: []const u8, xge: bool, @"opcode-min": u8, @"opcode-max": u8 },

        @"error": struct { name: []const u8, number: u32 },
        errorcopy: Copy,

        field: Field,
        fieldref: []const u8,
        pad: struct { bytes: u8 },
        list: Field,
        length: void,
        fd: Name,
        exprfield: Field,

        op: struct { op: Op },
        unop: struct { op: Op },
        sumof: struct { ref: []const u8 },
        popcount: void,
        @"listelement-ref": void,
        paramref: struct { type: []const u8 },

        @"switch": Name,
        case: Name,
        bitcase: void,

        required_start_align: struct { @"align": u8, offset: u8 },

        doc: []const u8,
        brief: []const u8,
        description: []const u8,
        example: []const u8,
        see: Field,

        character_data: []const u8,

        pub const Name = struct { name: []const u8 };
        pub const Field = struct { name: []const u8, type: []const u8 };
        pub const Copy = struct { name: []const u8, number: u32, ref: []const u8 };

        pub const Op = enum(u8) {
            invalid,
            @"+" = '+',
            @"-" = '-',
            @"*" = '*',
            @"/" = '/',
            @"&amp;" = '&',
            @"&lt;" = '<',
            @"&gt;" = '>',
            @"&quot;" = '"',
            @"&apos;" = '\'',
        };
    };

    pub fn init(gpa: std.mem.Allocator) @This() {
        return .{ .gpa = gpa, .tree = .init(.root) };
    }

    pub fn deinit(self: *@This()) void {
        self.tree.deinit(self.gpa);
    }

    pub fn parse(self: *@This(), parser: *xml.Parser) !void {
        var stack: std.ArrayList(*Tree.Node) = .empty;
        defer stack.deinit(self.gpa);

        while (parser.next()) |event| switch (event) {
            .open_tag => |tag_str| {
                if (std.mem.eql(u8, tag_str, "doc")) {
                    while (parser.next()) |sub_event| if (sub_event == .close_tag and std.mem.eql(u8, sub_event.close_tag, "doc")) continue;
                }

                const tag = std.meta.stringToEnum(std.meta.Tag(NodeValue), tag_str) orelse std.debug.panic("invalid tag: {s}", .{tag_str});

                const active_node = stack.getLastOrNull() orelse &self.tree.root;

                const node: *Tree.Node = switch (tag) {
                    // .doc, .brief, .description => continue,
                    inline else => |comptime_tag| node: {
                        const value = @unionInit(Tree.Node.Value, @tagName(comptime_tag), std.mem.zeroes(@FieldType(Tree.Node.Value, @tagName(comptime_tag))));
                        break :node try active_node.addChild(self.gpa, value);
                    },
                };
                try stack.append(self.gpa, node);
            },
            .close_tag => {
                _ = stack.pop();
            },
            .attribute => |attribute| {
                const node = stack.getLastOrNull() orelse std.debug.panic("attribute '{s}' requires node", .{attribute.name});
                switch (std.meta.activeTag(node.value)) {
                    inline else => |tag| {
                        const field_name = @tagName(tag);
                        switch (@typeInfo(@FieldType(Tree.Node.Value, field_name))) {
                            .@"struct" => {
                                helper.assignFieldBySliceWithSlice(&@field(node.value, field_name), attribute.name, attribute.raw_value);
                            },
                            else => {},
                        }
                    },
                }
            },
            .character_data => |character_data| {
                const node = stack.getLastOrNull() orelse std.debug.panic("character_data '{s}' requires node", .{character_data});

                switch (std.meta.activeTag(node.value)) {
                    inline else => |tag| {
                        const field_name = @tagName(tag);
                        const FieldType = @FieldType(Tree.Node.Value, field_name);
                        if (helper.parseValue(FieldType, character_data)) |value| {
                            @field(node.value, field_name) = value;
                            continue;
                        }

                        _ = try node.addChild(self.gpa, .{ .character_data = character_data });
                    },
                }
            },
            else => {},
        };
    }
};

/// Intermediate Representation
pub const Ir = struct {
    gpa: std.mem.Allocator,
    protocols: std.ArrayList(Protocol) = .empty,

    pub const Protocol = struct {
        name: []const u8,
        major_version: u8,
        minor_version: u8,

        xids: std.ArrayList(Xid) = .empty,
        enums: std.ArrayList(Enum) = .empty,
        bitmasks: std.ArrayList(Bitmask) = .empty,
        unions: std.ArrayList(Union) = .empty,
        structs: std.ArrayList(Struct) = .empty,
        events: std.ArrayList(Event) = .empty,
        requests: std.ArrayList(Request) = .empty,

        pub const Xid = struct {
            name: []const u8,
        };

        pub const Field = union(enum) {
            basic: Basic,
            pad: u8,
            list: struct {
                name: []const u8,
                type: []const u8,
                ref: Ref,
            },

            pub const Basic = struct {
                name: []const u8,
                type: []const u8,
            };

            pub const Ref = union(enum) {
                field: *Field,
                expression: void,
            };
        };

        pub const Enum = struct {
            name: []const u8,
            fields: std.ArrayList(@This().Field) = .empty,
            /// null when generic/unknown
            tag_type: ?[]const u8 = null,

            pub const Field = struct {
                name: []const u8,
                value: u64,
            };
        };

        pub const Bitmask = struct {
            name: []const u8,
            fields: std.ArrayList(@This().Field) = .empty,
            tag_type: ?[]const u8 = null,

            pub const Field = struct {
                name: []const u8,
                bit: u8,
            };
        };

        pub const Union = struct {
            name: []const u8,
            fields: std.ArrayList(Field.Basic) = .empty,
        };

        pub const Struct = struct {
            name: []const u8,
            fields: std.ArrayList(Field) = .empty,
        };

        pub const Event = struct {
            name: []const u8,
            number: u32,
            fields: std.ArrayList(Field) = .empty,
        };

        pub const Request = struct {
            name: []const u8,
            opcode: u8,
            fields: std.ArrayList(Field) = .empty,
            reply: ?Reply = null,

            pub const Reply = struct {
                fields: std.ArrayList(Field) = .empty,
            };
        };
    };

    pub fn init(gpa: std.mem.Allocator) @This() {
        return .{ .gpa = gpa };
    }

    pub fn deinit(self: *@This()) void {
        for (self.protocols.items) |*protocol| {
            for (protocol.enums.items) |*@"enum"| @"enum".fields.deinit(self.gpa);
            for (protocol.bitmasks.items) |*bitmask| bitmask.fields.deinit(self.gpa);
            for (protocol.unions.items) |*@"union"| @"union".fields.deinit(self.gpa);
            for (protocol.structs.items) |*@"struct"| @"struct".fields.deinit(self.gpa);
            for (protocol.events.items) |*event| event.fields.deinit(self.gpa);
            for (protocol.requests.items) |*request| request.fields.deinit(self.gpa);

            protocol.xids.deinit(self.gpa);
            protocol.enums.deinit(self.gpa);
            protocol.bitmasks.deinit(self.gpa);
            protocol.unions.deinit(self.gpa);
            protocol.structs.deinit(self.gpa);
            protocol.events.deinit(self.gpa);
            protocol.requests.deinit(self.gpa);
        }
        self.protocols.deinit(self.gpa);
    }

    pub fn emitter(self: @This(), writer: *std.Io.Writer) !IrEmitter {
        const names = try self.gpa.create(IrEmitter.NamePool);
        names.* = .{ .arena = .init(self.gpa) };

        return .{
            .gpa = self.gpa,
            .writer = writer,
            .ir = &self,
            .names = names,
        };
    }

    pub fn parse(self: *@This(), parser: ProtocolParser) !void {
        for (parser.tree.root.children.items) |child| {
            try self.parseProtocol(child);
        }
    }

    pub fn parseProtocol(self: *@This(), node: *ProtocolParser.Node) !void {
        std.debug.assert(node.value == .xcb);
        const xcb = node.value.xcb;
        const protocol = try self.protocols.addOne(self.gpa);
        protocol.* = .{
            .name = xcb.header,
            .major_version = xcb.@"major-version",
            .minor_version = xcb.@"minor-version",
        };

        for (node.children.items) |child| switch (child.value) {
            .xidtype => try protocol.xids.append(self.gpa, try self.parseXid(child)),
            .@"enum" => try protocol.enums.append(self.gpa, try self.parseEnum(child)),
            .@"union" => try protocol.unions.append(self.gpa, try self.parseUnion(child)),
            .@"struct" => try protocol.structs.append(self.gpa, try self.parseStruct(child)),
            .event => try protocol.events.append(self.gpa, try self.parseEvent(child)),
            .request => try protocol.requests.append(self.gpa, try self.parseRequest(child)),
            else => {},
        };
    }
    pub fn parseXid(self: @This(), node: *ProtocolParser.Node) !Ir.Protocol.Xid {
        _ = self;
        const value = node.value.xidtype;
        return .{ .name = value.name };
    }
    pub fn parseEnum(self: @This(), node: *ProtocolParser.Node) !Ir.Protocol.Enum {
        _ = self;
        const value = node.value.@"enum";
        return .{ .name = value.name };
    }
    pub fn parseBitmask(self: @This(), node: *ProtocolParser.Node) !Ir.Protocol.Bitmask {
        _ = self;
        const value = node.value.@"enum";
        return .{ .name = value.name };
    }
    pub fn parseUnion(self: @This(), node: *ProtocolParser.Node) !Ir.Protocol.Union {
        _ = self;
        const value = node.value.@"union";
        return .{ .name = value.name };
    }
    pub fn parseStruct(self: @This(), node: *ProtocolParser.Node) !Ir.Protocol.Struct {
        const value = node.value.@"struct";
        const fields = try self.parseFields(node);
        return .{ .name = value.name, .fields = fields };
    }
    pub fn parseEvent(self: @This(), node: *ProtocolParser.Node) !Ir.Protocol.Event {
        const value = node.value.event;
        const fields = try self.parseFields(node);
        return .{ .name = value.name, .number = value.number, .fields = fields };
    }
    pub fn parseRequest(self: @This(), node: *ProtocolParser.Node) !Ir.Protocol.Request {
        const value = node.value.request;
        const fields = try self.parseFields(node);
        return .{ .name = value.name, .opcode = value.opcode, .fields = fields };
    }
    pub fn parseFields(self: @This(), parent: *ProtocolParser.Node) !std.ArrayList(Ir.Protocol.Field) {
        var fields: std.ArrayList(Ir.Protocol.Field) = try .initCapacity(self.gpa, parent.children.items.len);
        for (parent.children.items) |child| switch (child.value) {
            .field => |field| try fields.append(self.gpa, .{ .basic = .{ .name = field.name, .type = field.type } }),
            .pad => |pad| try fields.append(self.gpa, .{ .pad = pad.bytes }),
            .list => |list| {
                try fields.append(self.gpa, .{ .list = .{ .name = list.name, .type = list.type, .ref = .expression } });
            },
            .fd => |fd| try fields.append(self.gpa, .{ .basic = .{ .name = fd.name, .type = "std.posix.fd_t" } }),

            else => {},
        };
        return fields;
    }
};

pub const IrEmitter = struct {
    gpa: std.mem.Allocator,
    writer: *std.Io.Writer,
    ir: *const Ir,
    names: *NamePool,

    pub const NamePool = struct {
        arena: std.heap.ArenaAllocator,

        pub const zig_keywords: []const [:0]const u8 = &.{
            "error",
            "suspend",
        };

        pub fn snakeCase(self: *@This(), name: []const u8) ![]u8 {
            const gpa = self.arena.allocator();
            var buf = try std.ArrayList(u8).initCapacity(gpa, name.len + 4);

            for (name, 0..) |c, i| {
                if (!std.ascii.isAlphanumeric(c)) {
                    if (buf.items.len > 0 and buf.items[buf.items.len - 1] != '_') try buf.append(gpa, '_');
                    continue;
                }

                if (i != 0 and std.ascii.isUpper(c) and buf.items[buf.items.len - 1] != '_') try buf.append(gpa, '_');

                try buf.append(gpa, std.ascii.toLower(c));
            }

            for (zig_keywords) |keyword| if (std.mem.eql(u8, buf.items, keyword)) {
                defer buf.deinit(gpa);

                const quoted_len = buf.items.len + 3;
                var quoted = try gpa.alloc(u8, quoted_len);

                @memcpy(quoted[0..2], "@\"");
                @memcpy(quoted[2 .. quoted_len - 1], buf.items.ptr);
                quoted[quoted_len - 1] = '"';

                return quoted;
            };

            return buf.toOwnedSlice(gpa);
        }

        pub fn camelCase(self: *@This(), name: []const u8) ![]u8 {
            const gpa = self.arena.allocator();
            var buf = try std.ArrayList(u8).initCapacity(gpa, name.len);

            var upper_next = false;
            for (name, 0..) |c, i| {
                if (!std.ascii.isAlphanumeric(c)) {
                    upper_next = true;
                    continue;
                }

                const out = if (i == 0) std.ascii.toLower(c) else if (upper_next) std.ascii.toUpper(c) else c;

                try buf.append(gpa, out);
                upper_next = false;
            }

            return buf.toOwnedSlice(gpa);
        }

        pub fn pascalCase(self: *@This(), name: []const u8) ![]u8 {
            const camel = try self.camelCase(name);
            if (camel.len == 0) return camel;
            camel[0] = std.ascii.toUpper(camel[0]);
            return camel;
        }

        pub fn screamingCase(self: *@This(), name: []const u8) ![]u8 {
            const snake_case = try self.snakeCase(name);
            for (snake_case) |*char| char = std.ascii.toUpper(char);
            return snake_case;
        }
    };

    pub fn deinit(self: @This()) void {
        self.names.arena.deinit();
        self.gpa.destroy(self.names);
    }

    pub fn emit(self: @This()) !void {
        for (self.ir.protocols.items) |protocol| {
            try self.emitProtocol(protocol);
        }
    }

    pub fn emitBlockEnd(self: @This()) !void {
        const w = self.writer;
        try w.writeAll("};\n\n");
    }

    pub fn emitProtocol(self: @This(), protocol: Ir.Protocol) !void {
        const w = self.writer;
        try w.print(
            \\pub const {s} = struct {{
            \\  pub const major_version = {d};
            \\  pub const minor_version = {d};
            \\
            \\
        , .{
            try self.names.snakeCase(protocol.name),
            protocol.major_version,
            protocol.minor_version,
        });

        try w.writeAll("pub const Opcode = enum(u8) {\n");
        for (protocol.requests.items) |request| {
            const opcode_name = try self.names.snakeCase(request.name);
            try w.print("{s} = {d},\n", .{ opcode_name, request.opcode });
        }
        try self.emitBlockEnd();

        for (protocol.xids.items) |xid| try self.emitXid(xid);
        for (protocol.enums.items) |@"enum"| try self.emitEnum(@"enum");
        for (protocol.bitmasks.items) |bitmask| try self.emitBitmask(bitmask);
        for (protocol.unions.items) |@"union"| try self.emitUnion(@"union");
        for (protocol.structs.items) |@"struct"| try self.emitStruct(@"struct");
        for (protocol.events.items) |event| try self.emitEvent(event);
        for (protocol.requests.items) |request| try self.emitRequest(request);

        try self.emitBlockEnd();
    }
    pub fn emitXid(self: @This(), xid: Ir.Protocol.Xid) !void {
        const w = self.writer;
        const name = try self.names.pascalCase(xid.name);
        try w.print("pub const {s} = enum(u32) {{_,", .{name});
        try self.emitBlockEnd();
    }
    pub fn emitEnum(self: @This(), @"enum": Ir.Protocol.Enum) !void {
        const w = self.writer;
        const name = try self.names.pascalCase(@"enum".name);
        if (@"enum".tag_type) |tag_type| {
            try w.print("pub const {s} = enum({s}) {{\n", .{ name, tag_type });
        } else {
            try w.print(
                \\pub fn {s}(Tag: type) type {{
                \\  return enum(Tag) {{
                \\
            , .{name});
        }

        for (@"enum".fields.items) |field| {
            try w.print("{s} = {d},\n", .{ field.name, field.value });
        }

        if (@"enum".tag_type != null)
            try self.emitBlockEnd()
        else
            try w.writeAll("};\n}\n\n");
    }
    pub fn emitBitmask(self: @This(), bitmask: Ir.Protocol.Bitmask) !void {
        _ = self;
        _ = bitmask;
    }
    pub fn emitUnion(self: @This(), @"union": Ir.Protocol.Union) !void {
        const w = self.writer;
        const name = try self.names.pascalCase(@"union".name);
        try w.print("pub const {s} = extern union {{\n", .{name});

        for (@"union".fields.items) |field| {
            const field_name = try self.names.snakeCase(field.name);
            try w.print("{s}: {s},\n", .{ field_name, field.type });
        }

        try self.emitBlockEnd();
    }
    pub fn emitStruct(self: @This(), @"struct": Ir.Protocol.Struct) !void {
        const w = self.writer;
        const name = try self.names.pascalCase(@"struct".name);
        try w.print("pub const {s} = extern struct {{\n", .{name});
        try self.emitFields(@"struct".fields.items);
        try self.emitBlockEnd();
    }
    pub fn emitEvent(self: @This(), event: Ir.Protocol.Event) !void {
        _ = self;
        _ = event;
    }
    pub fn emitRequest(self: @This(), request: Ir.Protocol.Request) !void {
        const w = self.writer;
        const name = try self.names.pascalCase(request.name);
        const opcode_name = try self.names.snakeCase(request.name);
        try w.print("pub const {s}Request = extern struct {{\n", .{name});
        try self.emitFields(request.fields.items);
        try w.writeByte('\n');
        try w.print("pub const opcode: Opcode = .{s};\n", .{opcode_name});
        try self.emitBlockEnd();
    }

    pub fn emitFields(self: @This(), fields: []Ir.Protocol.Field) !void {
        const w = self.writer;
        var pad_field_count: usize = 0;
        for (fields) |field| switch (field) {
            .basic => |basic| {
                const name = try self.names.snakeCase(basic.name);
                try w.print("{s}: {s},\n", .{ name, basic.type });
            },
            .pad => |pad| {
                try w.print("pad{d}: [{d}]u8 = @splat(0),\n", .{ pad_field_count, pad });
                pad_field_count += 1;
            },
            .list => |list| {
                const name = try self.names.snakeCase(list.name);
                try w.print("{s}_ptr: [*]{s},\n", .{ name, list.type });
            },
        };
    }
};

pub fn FamilyTree(NodeValue: type) type {
    return struct {
        root: Node,

        pub const Node = struct {
            parent: *Node,
            value: NodeValue,
            children: std.ArrayList(*Node) = .empty,

            pub const Value = NodeValue;

            pub fn addChild(self: *@This(), gpa: std.mem.Allocator, value: NodeValue) !*Node {
                const child = try self.children.addOne(gpa);
                child.* = try gpa.create(Node);
                child.*.* = .{
                    .parent = self,
                    .value = value,
                };
                return child.*;
            }

            pub fn deinit(self: *@This(), gpa: std.mem.Allocator) void {
                for (self.children.items) |child| {
                    child.deinit(gpa);
                    gpa.destroy(child);
                }
                self.children.deinit(gpa);
            }
        };

        pub fn init(root: NodeValue) @This() {
            return .{ .root = .{ .parent = undefined, .value = root } };
        }

        pub fn deinit(self: *@This(), gpa: std.mem.Allocator) void {
            self.root.deinit(gpa);
        }
    };
}

pub const helper = struct {
    pub fn assignFieldBySliceWithSlice(lhs: anytype, field_name: []const u8, field_value: []const u8) void {
        if (@typeInfo(@TypeOf(lhs)) != .pointer) @compileError("cannot mutate non pointer type");
        inline for (std.meta.fields(std.meta.Child(@TypeOf(lhs)))) |field| {
            if (std.mem.eql(u8, field.name, field_name)) {
                if (parseValue(field.type, field_value)) |value| @field(lhs.*, field.name) = value;
            }
        }
    }

    pub fn parseValue(comptime T: type, value: []const u8) ?T {
        return switch (@typeInfo(T)) {
            .int => std.fmt.parseInt(T, value, 10) catch null,
            .float => std.fmt.parseFloat(T, value) catch null,
            .@"enum" => std.meta.stringToEnum(T, value),
            .pointer => |pointer| if (pointer.child == u8) value else return null,
            .optional => |optional| parseValue(optional.child, value),
            else => null,
        };
    }
};
