const std = @import("std");
const assert = std.debug.assert;

const log = std.log.scoped(.@"zig-xcb");

const xml = @import("xml.zig");

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const gpa = init.gpa;

    var protocols: std.ArrayList([]const u8) = .empty;
    defer protocols.deinit(gpa);

    var out_path_opt: ?[]const u8 = null;

    var args = init.minimal.args.iterate();

    while (args.next()) |arg| {
        if (std.mem.eql(u8, arg, "-i")) {
            const protocol_path = args.next() orelse return error.MissingArg;
            try protocols.append(gpa, protocol_path);
        } else if (std.mem.eql(u8, arg, "-o")) {
            out_path_opt = args.next() orelse return error.MissingArg;
        }
    }

    const out_path = out_path_opt orelse return error.MissingArg;
    std.log.info("{s}", .{out_path});

    var documents: std.ArrayList([]const u8) = .empty;
    defer {
        for (documents.items) |document|
            gpa.free(document);
        documents.deinit(gpa);
    }

    var tree: Tree = .init(gpa);
    defer tree.deinit();

    for (protocols.items) |protocol| {
        var protocol_file = try std.Io.Dir.openFileAbsolute(io, protocol, .{});
        defer protocol_file.close(io);
        var file_reader = protocol_file.reader(io, &.{});
        const document = try file_reader.interface.allocRemaining(gpa, .unlimited);
        try documents.append(gpa, document);

        var parser: xml.Parser = .init(document);
        try tree.parse(&parser);
    }

    var buffer: std.Io.Writer.Allocating = .init(gpa);
    const writer = &buffer.writer;
    try writer.writeAll(
        \\//! Generated by xcb-scanner
        \\
        \\
    );
    try writer.writeAll(@embedFile("core.zig"));
    try writer.writeByte('\n');
    try tree.emit(writer);

    const generated = try buffer.toOwnedSliceSentinel(0);
    defer gpa.free(generated);

    var zig_tree = try std.zig.Ast.parse(gpa, generated, .zig);
    defer zig_tree.deinit(gpa);

    const out_file = try std.Io.Dir.createFileAbsolute(io, out_path, .{});
    defer out_file.close(io);

    if (zig_tree.errors.len != 0) {
        try std.zig.printAstErrorsToStderr(gpa, io, zig_tree, out_path, .auto);
        try out_file.writeStreamingAll(io, generated);
        return error.ParseError;
    }

    var out_buf: [4096]u8 = undefined;
    var out_writer = out_file.writer(io, &out_buf);

    try zig_tree.render(gpa, &out_writer.interface, .{});

    try out_writer.interface.flush();
}

pub const Tree = struct {
    gpa: std.mem.Allocator,
    protocols: std.ArrayList(Protocol) = .empty,

    pub const Tag = enum {
        none, // none
        xcb,
        import,
        type,
        typedef,
        xidtype,
        xidunion,
        event,
        @"error",
        @"struct",
        request,
        reply,
        field,
        pad,
        list,
        fieldref,
        @"enum",
        item,
        value,
        bit,
        op,
        doc,
        brief,
        description,
    };

    pub const Protocol = struct {
        header: ?[]const u8 = null,
        @"extension-xname": ?[]const u8 = null,
        @"extension-name": ?[]const u8 = null,
        @"extension-multiword": bool = false,
        @"major-version": u8 = 0,
        @"minor-version": u8 = 0,

        structs: std.ArrayList(Struct) = .empty,
        requests: std.ArrayList(Request) = .empty,
    };

    pub const Field = union(enum) {
        normal: struct {
            name: []const u8 = "",
            type: []const u8 = "",
        },
        list: struct {
            name: []const u8 = "",
            type: []const u8 = "",
            fieldref: *Field = undefined,
        },
        pad: struct {
            bytes: u8 = 0,
        },
    };

    pub const Struct = struct {
        name: []const u8 = "",
        fields: *std.ArrayList(Field) = undefined,
    };

    pub const Request = struct {
        name: []const u8 = "",
        opcode: u8 = 0,
        fields: *std.ArrayList(Field) = undefined,
        reply: ?*Reply = null,
    };

    pub const Reply = struct {
        fields: *std.ArrayList(Field) = undefined,
    };

    pub fn init(gpa: std.mem.Allocator) @This() {
        return .{ .gpa = gpa };
    }

    pub fn deinit(self: *@This()) void {
        for (self.protocols.items) |*protocol| {
            for (protocol.structs.items) |@"struct"| {
                @"struct".fields.deinit(self.gpa);
                self.gpa.destroy(@"struct".fields);
            }
            protocol.structs.deinit(self.gpa);

            for (protocol.requests.items) |request| {
                request.fields.deinit(self.gpa);
                self.gpa.destroy(request.fields);
                if (request.reply) |reply| {
                    reply.fields.deinit(self.gpa);
                    self.gpa.destroy(reply.fields);
                    self.gpa.destroy(reply);
                }
            }
            protocol.requests.deinit(self.gpa);
        }
        self.protocols.deinit(self.gpa);
    }

    pub fn parse(self: *@This(), parser: *xml.Parser) !void {
        var protocol: ?*Protocol = null;
        var decl: ?union(enum) {
            @"struct": *Struct,
            request: *Request,
            reply: *Reply,
        } = null;
        var field: ?*Field = null;

        var tag: Tag = .none;

        while (parser.next()) |event| switch (event) {
            .open_tag => |tag_str| {
                tag = std.meta.stringToEnum(Tag, tag_str) orelse std.debug.panic("unknown tag: {s}", .{tag_str});
                switch (tag) {
                    .none => {},
                    .xcb => {
                        protocol = try self.protocols.addOne(self.gpa);
                        protocol.?.* = .{};
                    },
                    .import => {},
                    .type => {},
                    .typedef => {},
                    .xidtype => {},
                    .xidunion => {},
                    .event => {},
                    .@"error" => {},
                    .@"struct" => {
                        const @"struct" = try protocol.?.structs.addOne(self.gpa);
                        @"struct".* = .{
                            .fields = try self.gpa.create(std.ArrayList(Field)),
                        };
                        @"struct".fields.* = .empty;
                        decl = .{ .@"struct" = @"struct" };
                    },
                    .request => {
                        const request = try protocol.?.requests.addOne(self.gpa);
                        request.* = .{
                            .fields = try self.gpa.create(std.ArrayList(Field)),
                        };
                        request.fields.* = .empty;
                        decl = .{ .request = request };
                    },
                    .reply => {
                        if (decl == null) continue;
                        const reply = try self.gpa.create(Reply);
                        reply.* = .{
                            .fields = try self.gpa.create(std.ArrayList(Field)),
                        };
                        reply.fields.* = .empty;
                        decl.?.request.reply = reply;
                        decl = .{ .reply = reply };
                    },
                    .field => {
                        const fields = switch (decl orelse continue) {
                            .@"struct" => |@"struct"| @"struct".fields,
                            .request => |request| request.fields,
                            .reply => |reply| reply.fields,
                        };

                        field = try fields.addOne(self.gpa);
                        field.?.* = .{ .normal = .{} };
                    },
                    .pad => {
                        const fields = switch (decl orelse continue) {
                            .@"struct" => |@"struct"| @"struct".fields,
                            .request => |request| request.fields,
                            .reply => |reply| reply.fields,
                        };

                        field = try fields.addOne(self.gpa);
                        field.?.* = .{ .pad = .{} };
                    },
                    .list => {
                        const fields = switch (decl orelse continue) {
                            .@"struct" => |@"struct"| @"struct".fields,
                            .request => |request| request.fields,
                            .reply => |reply| reply.fields,
                        };

                        field = try fields.addOne(self.gpa);
                        field.?.* = .{ .list = .{} };
                    },
                    .fieldref => {},
                    .@"enum" => {},
                    .value => {},
                    .item => {},
                    .bit => {},
                    .op => {},
                    .doc => {
                        while (parser.next()) |sub_event| if (sub_event == .close_tag and std.mem.eql(u8, sub_event.close_tag, @tagName(tag))) continue;
                    },
                    .brief, .description => {},
                }
            },
            .close_tag => {
                switch (tag) {
                    .xcb => {
                        protocol = null;
                        decl = null;
                        field = null;
                    },
                    .field, .pad, .list => {
                        field = null;
                    },
                    else => {},
                }
                tag = .none;
            },
            .attribute => |attribute| switch (tag) {
                .xcb => helper.assignFieldFromSliceWithSlice(protocol.?, attribute.name, attribute.raw_value),
                .@"struct" => helper.assignFieldFromSliceWithSlice(decl.?.@"struct", attribute.name, attribute.raw_value),
                .request => helper.assignFieldFromSliceWithSlice(decl.?.request, attribute.name, attribute.raw_value),
                .reply => helper.assignFieldFromSliceWithSlice(decl.?.reply, attribute.name, attribute.raw_value),
                .field => helper.assignFieldFromSliceWithSlice(&field.?.normal, attribute.name, attribute.raw_value),
                .pad => helper.assignFieldFromSliceWithSlice(&field.?.pad, attribute.name, attribute.raw_value),
                .list => helper.assignFieldFromSliceWithSlice(&field.?.list, attribute.name, attribute.raw_value),
                else => {},
                // std.log.info("unhandled: {s}: {s}", .{ attribute.name, attribute.raw_value });
            },
            .character_data => {},
            else => {},
        };
    }

    pub fn emit(self: *@This(), w: *std.Io.Writer) !void {
        for (self.protocols.items) |protocol| {
            try w.print(
                \\pub const {s} = struct {{
                \\  pub const major_version = {d};
                \\  pub const minor_version = {d};
                \\  pub const extension_multiword = {};
                \\
                \\
            , .{
                protocol.header orelse
                    protocol.@"extension-xname" orelse
                    protocol.@"extension-name".?,
                protocol.@"major-version",
                protocol.@"minor-version",
                protocol.@"extension-multiword",
            });

            try w.writeAll("pub const Opcode = enum(u8) {\n");
            for (protocol.requests.items) |request| {
                try w.print("{s} = {d},\n", .{ request.name, request.opcode });
            }
            try w.writeAll("};\n\n");

            for (protocol.structs.items) |@"struct"| {
                try w.print("pub const {s} = extern struct {{", .{@"struct".name});
                try emitFields(w, @"struct".fields.items);
                try w.writeAll("};\n\n");
            }

            for (protocol.requests.items) |request| {
                try w.print(
                    \\pub const {s} = extern struct {{
                    \\  pub const opcode: Opcode = .{s}; 
                    \\
                    \\
                , .{
                    request.name,
                    request.name,
                });

                try emitFields(w, request.fields.items);

                if (request.reply) |reply| {
                    try w.writeAll("\npub const Reply = extern struct {\n");
                    try emitFields(w, reply.fields.items);
                    try w.writeAll("};\n");
                }

                try w.writeAll("};\n\n");
            }

            try w.writeAll("};\n\n");
        }
    }

    pub fn emitFields(w: *std.Io.Writer, fields: []Field) !void {
        var pad_count: usize = 0;
        for (fields) |field| switch (field) {
            .normal => |normal| {
                try w.print("{s}: {s},\n", .{ normal.name, normal.type });
            },
            .pad => |pad| {
                if (pad.bytes == 1)
                    try w.print("pad{d}: u8 = 0,\n", .{pad_count})
                else
                    try w.print("pad{d}: [{d}]u8 = @splat(0),\n", .{ pad_count, pad.bytes });
                pad_count += 1;
            },
            .list => |list| {
                _ = list;
                // try w.print("{s} [*]{s}, // {s}\n", .{ list.name, list.type, "..." });
            },
        };
    }
};

pub const helper = struct {
    pub fn assignFieldFromSliceWithSlice(lhs: anytype, field_name: []const u8, field_value: []const u8) void {
        if (@typeInfo(@TypeOf(lhs)) != .pointer) @compileError("cannot not mutate non pointer type");
        inline for (std.meta.fields(std.meta.Child(@TypeOf(lhs)))) |field| {
            if (std.mem.eql(u8, field.name, field_name)) {
                if (parseValue(field.type, field_value)) |value| @field(lhs.*, field.name) = value;
            }
        }
    }

    pub fn parseValue(comptime T: type, value: []const u8) ?T {
        return switch (@typeInfo(T)) {
            .int => std.fmt.parseInt(T, value, 10) catch null,
            .float => std.fmt.parseFloat(T, value) catch null,
            .@"enum" => std.meta.stringToEnum(T, value),
            .pointer => |pointer| if (pointer.child == u8) value else return null,
            .optional => |optional| parseValue(optional.child, value),
            else => null,
        };
    }
};
