const std = @import("std");
const assert = std.debug.assert;

const log = std.log.scoped(.@"zig-xcb");

const xml = @import("xml.zig");

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const gpa = init.gpa;

    var protocols: std.ArrayList([]const u8) = .empty;
    defer protocols.deinit(gpa);

    var out_path_opt: ?[]const u8 = null;

    var args = init.minimal.args.iterate();

    while (args.next()) |arg| {
        if (std.mem.eql(u8, arg, "-i")) {
            const protocol_path = args.next() orelse return error.MissingArg;
            try protocols.append(gpa, protocol_path);
        } else if (std.mem.eql(u8, arg, "-o")) {
            out_path_opt = args.next() orelse return error.MissingArg;
        }
    }

    const out_path = out_path_opt orelse return error.MissingArg;
    log.info("{s}", .{out_path});

    var documents: std.ArrayList([]const u8) = .empty;
    defer {
        for (documents.items) |document|
            gpa.free(document);
        documents.deinit(gpa);
    }

    var xml_deserializer: XmlDeserializer = .init(gpa);
    defer xml_deserializer.deinit();

    for (protocols.items, 0..) |protocol, i| {
        var protocol_file = try std.Io.Dir.openFileAbsolute(io, protocol, .{});
        defer protocol_file.close(io);
        var file_reader = protocol_file.reader(io, &.{});
        const document = try file_reader.interface.allocRemaining(gpa, .unlimited);
        try documents.append(gpa, document);

        var parser: xml.Parser = .init(document);
        std.log.info("[{d}/{d}] {s}", .{ i + 1, protocols.items.len, std.Io.Dir.path.basename(protocol) });
        try xml_deserializer.parse(&parser);
    }

    var buffer: std.Io.Writer.Allocating = .init(gpa);
    const writer = &buffer.writer;
    try writer.writeAll(
        \\//! Generated by xcb-scanner
        \\
        \\
    );
    try writer.writeAll(@embedFile("core.zig"));
    try writer.writeByte('\n');

    try xml_deserializer.emit(writer);

    const generated = try buffer.toOwnedSliceSentinel(0);
    defer gpa.free(generated);

    var zig_tree = try std.zig.Ast.parse(gpa, generated, .zig);
    defer zig_tree.deinit(gpa);

    const out_file = try std.Io.Dir.createFileAbsolute(io, out_path, .{});
    defer out_file.close(io);

    if (zig_tree.errors.len != 0) {
        try std.zig.printAstErrorsToStderr(gpa, io, zig_tree, out_path, .auto);
        try out_file.writeStreamingAll(io, generated);
        return error.ParseError;
    }

    var out_buf: [4096]u8 = undefined;
    var out_writer = out_file.writer(io, &out_buf);

    try zig_tree.render(gpa, &out_writer.interface, .{});

    try out_writer.interface.flush();
}

pub const XmlDeserializer = struct {
    gpa: std.mem.Allocator,
    tree: Tree,

    pub const Tree = FamilyTree(Node);

    pub const Node = union(enum) {
        root,
        xcb: struct {
            header: []const u8 = "invalid",
            @"extension-xname": ?[]const u8 = null,
            @"extension-name": ?[]const u8 = null,
            @"extension-multiword": bool = false,
            @"major-version": u8 = 0,
            @"minor-version": u8 = 0,
        },
        import: []const u8,
        typedef: struct { oldname: []const u8, newname: []const u8 },
        type: []const u8,
        xidtype: Name,
        xidunion: Name,
        @"enum": Name,
        enumref: struct { ref: []const u8 },
        item: Name,
        value: u64,
        bit: u64,
        @"struct": Name,
        @"union": Name,
        request: struct { name: []const u8, opcode: u8 },
        reply: void,

        event: struct { name: []const u8, number: u32 },
        eventcopy: Copy,
        eventstruct: Name,
        allowed: struct { extension: []const u8, xge: bool, @"opcode-min": u8, @"opcode-max": u8 },

        @"error": struct { name: []const u8, number: u32 },
        errorcopy: Copy,

        field: Field,
        fieldref: []const u8,
        pad: struct { bytes: u8 },
        list: Field,
        length: void,
        fd: Name,
        exprfield: Field,

        op: struct { op: Op },
        unop: struct { op: Op },
        sumof: struct { ref: []const u8 },
        popcount: void,
        @"listelement-ref": void,
        paramref: struct { type: []const u8 },

        @"switch": Name,
        case: Name,
        bitcase: void,

        required_start_align: struct { @"align": u8, offset: u8 },

        doc: []const u8,
        brief: []const u8,
        description: []const u8,
        example: []const u8,
        see: Field,

        character_data: []const u8,

        pub const Name = struct { name: []const u8 };
        pub const Field = struct { name: []const u8, type: []const u8 };
        pub const Copy = struct { name: []const u8, number: u32, ref: []const u8 };

        pub const Op = enum(u8) {
            invalid,
            @"+" = '+',
            @"-" = '-',
            @"*" = '*',
            @"/" = '/',
            @"&amp;" = '&',
            @"&lt;" = '<',
            @"&gt;" = '>',
            @"&quot;" = '"',
            @"&apos;" = '\'',
        };
    };

    pub fn init(gpa: std.mem.Allocator) @This() {
        return .{ .gpa = gpa, .tree = .init(.root) };
    }

    pub fn deinit(self: *@This()) void {
        self.tree.deinit(self.gpa);
    }

    pub fn parse(self: *@This(), parser: *xml.Parser) !void {
        var stack: std.ArrayList(*Tree.Node) = .empty;
        defer stack.deinit(self.gpa);

        while (parser.next()) |event| switch (event) {
            .open_tag => |tag_str| {
                if (std.mem.eql(u8, tag_str, "doc")) {
                    while (parser.next()) |sub_event| if (sub_event == .close_tag and std.mem.eql(u8, sub_event.close_tag, "doc")) continue;
                }

                const tag = std.meta.stringToEnum(std.meta.Tag(Node), tag_str) orelse std.debug.panic("invalid tag: {s}", .{tag_str});

                const active_node = stack.getLastOrNull() orelse &self.tree.root;

                const node: *Tree.Node = switch (tag) {
                    // .doc, .brief, .description => continue,
                    inline else => |comptime_tag| node: {
                        const value = @unionInit(Tree.Node.Value, @tagName(comptime_tag), std.mem.zeroes(@FieldType(Tree.Node.Value, @tagName(comptime_tag))));
                        break :node try active_node.addChild(self.gpa, value);
                    },
                };
                try stack.append(self.gpa, node);
            },
            .close_tag => {
                _ = stack.pop();
            },
            .attribute => |attribute| {
                const node = stack.getLastOrNull() orelse std.debug.panic("attribute '{s}' requires node", .{attribute.name});
                switch (std.meta.activeTag(node.value)) {
                    inline else => |tag| {
                        const field_name = @tagName(tag);
                        switch (@typeInfo(@FieldType(Tree.Node.Value, field_name))) {
                            .@"struct" => {
                                helper.assignFieldBySliceWithSlice(&@field(node.value, field_name), attribute.name, attribute.raw_value);
                            },
                            else => {},
                        }
                    },
                }
            },
            .character_data => |character_data| {
                const node = stack.getLastOrNull() orelse std.debug.panic("character_data '{s}' requires node", .{character_data});

                switch (std.meta.activeTag(node.value)) {
                    inline else => |tag| {
                        const field_name = @tagName(tag);
                        const FieldType = @FieldType(Tree.Node.Value, field_name);
                        if (helper.parseValue(FieldType, character_data)) |value| {
                            @field(node.value, field_name) = value;
                            continue;
                        }

                        _ = try node.addChild(self.gpa, .{ .character_data = character_data });
                    },
                }
            },
            else => {},
        };
    }

    pub fn emit(self: *@This(), w: *std.Io.Writer) !void {
        try self.emitNode(w, &self.tree.root);
    }

    pub fn emitNode(self: *@This(), w: *std.Io.Writer, node: *Tree.Node) !void {
        switch (node.value) {
            .xcb => |xcb| {
                try w.print(
                    \\pub const {s} = struct {{
                    \\pub const major_version = {d};
                    \\pub const minor_version = {d};
                    \\
                , .{ xcb.header, xcb.@"major-version", xcb.@"minor-version" });

                try w.writeAll("pub const Opcode = enum(u8) {\n");
                for (node.children.items) |child| if (child.value == .request) {
                    const request = child.value.request;
                    try w.print("{s} = {d},\n", .{ request.name, request.opcode });
                };
                try w.writeAll("};\n");
            },
            .import => |import| {
                try w.print("// import {s}\n", .{import});
            },
            .@"struct" => |@"struct"| {
                try w.print("pub const {s} = extern struct {{\n", .{@"struct".name});
            },
            .@"union" => |@"union"| {
                try w.print("pub const {s} = extern struct {{\n", .{@"union".name});
            },
            .request => |request| {
                try w.print("pub const {s} = extern struct {{\n", .{request.name});
            },
            .reply => {
                try w.writeAll("pub const Reply = extern struct {\n");
            },
            .event => |event| {
                try w.print("pub const {s} = extern struct {{\n", .{event.name});
            },
            .@"error" => |@"error"| {
                try w.print("pub const {s} = extern struct {{\n", .{@"error".name});
            },
            .field => |field| {
                std.debug.assert(node.children.items.len == 0);
                try w.print("{s}: {s},\n", .{ field.name, "u32" });
            },

            .@"enum" => |@"enum"| {
                const is_bitmask = node.children.items[0].value == .bit;
                if (!is_bitmask)
                    try w.print("pub const {s} = enum(u32) {{\n", .{@"enum".name})
                else
                    try w.print("pub const {s} = packed struct {{\n", .{@"enum".name});
            },
            .item => |item| {
                try w.writeAll(item.name);
                switch (node.children.items[0].value) {
                    .value => |value| {
                        try w.print(" = {d},\n", .{value});
                    },
                    .bit => |bit| {
                        try w.print(": bool = false, // {d}\n", .{bit});
                    },
                    else => unreachable,
                }
            },
            .value, .bit => {},

            else => {
                try w.print("// {any}\n", .{node.value});
            },
        }

        for (node.children.items) |child| try self.emitNode(w, child);

        switch (node.value) {
            .xcb, .@"struct", .@"union", .request, .reply, .event, .@"error", .@"enum" => try w.writeAll("};\n\n"),
            else => {},
        }
    }
};

pub fn FamilyTree(NodeValue: type) type {
    return struct {
        root: Node,

        pub const Node = struct {
            parent: *Node,
            value: NodeValue,
            children: std.ArrayList(*Node) = .empty,

            pub const Value = NodeValue;

            pub fn addChild(self: *@This(), gpa: std.mem.Allocator, value: NodeValue) !*Node {
                const child = try self.children.addOne(gpa);
                child.* = try gpa.create(Node);
                child.*.* = .{
                    .parent = self,
                    .value = value,
                };
                return child.*;
            }

            pub fn deinit(self: *@This(), gpa: std.mem.Allocator) void {
                for (self.children.items) |child| {
                    child.deinit(gpa);
                    gpa.destroy(child);
                }
                self.children.deinit(gpa);
            }
        };

        pub fn init(root: NodeValue) @This() {
            return .{ .root = .{ .parent = undefined, .value = root } };
        }

        pub fn deinit(self: *@This(), gpa: std.mem.Allocator) void {
            self.root.deinit(gpa);
        }
    };
}

pub const helper = struct {
    pub fn assignFieldBySliceWithSlice(lhs: anytype, field_name: []const u8, field_value: []const u8) void {
        if (@typeInfo(@TypeOf(lhs)) != .pointer) @compileError("cannot mutate non pointer type");
        inline for (std.meta.fields(std.meta.Child(@TypeOf(lhs)))) |field| {
            if (std.mem.eql(u8, field.name, field_name)) {
                if (parseValue(field.type, field_value)) |value| @field(lhs.*, field.name) = value;
            }
        }
    }

    pub fn parseValue(comptime T: type, value: []const u8) ?T {
        return switch (@typeInfo(T)) {
            .int => std.fmt.parseInt(T, value, 10) catch null,
            .float => std.fmt.parseFloat(T, value) catch null,
            .@"enum" => std.meta.stringToEnum(T, value),
            .pointer => |pointer| if (pointer.child == u8) value else return null,
            .optional => |optional| parseValue(optional.child, value),
            else => null,
        };
    }
};
